export const fakeList = [
    {
        id: '1',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'adsa dadfafddf asf dsa  dfsaf d',
        time: '1:00 pm',
    },
    {
        id: '2',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'sa f',
        time: '1:01 pm',
    },
    {
        id: '3',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'sadejf ',
        time: '1:01 pm',
    },
    {
        id: '4',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'sadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaew',
        time: '1:01 pm',
    },
    {
        id: '5',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'sadew',
        time: '1:01 pm',
    },
    {
        id: '6',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message:
            'sadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaew',
        time: '1:01 pm',
    },
    {
        id: '7',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message:
            'sadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaewsadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaew',
        time: '1:01 pm',
    },
    {
        id: '8',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'sadfd sa fdsa ff ds faiojaew',
        time: '1:01 pm',
    },
    {
        id: '9',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'sadfd sa fdsa ff ds fa fds adfds af dsa dfsa fdafjiojaew',
        time: '1:01 pm',
    },
    {
        id: '10',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'sadojaew',
        time: '1:01 pm',
    },
    {
        id: '11',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'fdsf',
        time: '1:01 pm',
    },
    {
        id: '12',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'dsf sd f',
        time: '1:01 pm',
    },
    {
        id: '13',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message: 'd sf ',
        time: '1:01 pm',
    },
    {
        id: '14',
        userName: 'teacher1',
        avatar: '/MentorList/mentor_1.jpg',
        message:
            'fdssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss',
        time: '1:01 pm',
    },
    {
        id: '15',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'sdfs',
        time: '1:01 pm',
    },
    {
        id: '16',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'sdfs',
        time: '1:01 pm',
    },
    {
        id: '17',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'sdfs',
        time: '1:01 pm',
    },
    {
        id: '18',
        userName: 'teacher3',
        avatar: '/MentorList/mentor_5.jpg',
        message: 'sdfs',
        time: '1:01 pm',
    },
]
