import type { Mentor } from '~/container/MentorList/types'

export const MOCK_MENTOR_LIST: Mentor[] = [
    {
        id: 1,
        name: 'Olha Оnyshchenko',
        slug: 'olha-nyshchenko',
        country: 'Canada',
        company: 'lululemon',
        title: 'Project Manager',
        yearOfExperience: 7,
        totalSessions: 31,
        totalReviews: 20,
        avatar: '/MentorList/mentor_1.jpg',
    },
    {
        id: 2,
        name: 'Beau T.',
        slug: 'beau-t',
        country: 'Japan',
        company: 'PayPay',
        title: 'Senior Product Designer',
        yearOfExperience: 7,
        totalSessions: 31,
        totalReviews: 20,
        avatar: '/MentorList/mentor_2.jpg',
    },
    {
        id: 3,
        name: 'Nick H Borah',
        slug: 'nick-h-borah',
        country: 'Singapore',
        company: 'Freelance (ex-Google)',
        title: 'Product Design Leader',
        yearOfExperience: 7,
        totalSessions: 31,
        totalReviews: 20,
        avatar: '/MentorList/mentor_3.jpg',
    },
    {
        id: 4,
        name: 'Vamsi Yarlagadda',
        slug: 'vamsi-yarlagadda',
        country: 'United States',
        company: 'Seattle school district',
        title: 'HCM/Payroll Solutions Architect',
        yearOfExperience: 7,
        totalSessions: 31,
        totalReviews: 20,
        avatar: '/MentorList/mentor_4.jpg',
    },
    {
        id: 5,
        name: 'Anastasiia Kondratska',
        slug: 'anastasiia-kondratska',
        country: 'United States',
        company: 'EVENTEAM',
        title: 'Owner',
        yearOfExperience: 7,
        totalSessions: 31,
        totalReviews: 20,
        avatar: '/MentorList/mentor_5.jpg',
    },
]
